name: Go Application CI/CD

# Trigger pipeline saat ada push ke branch 'main'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout kode dari repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Setup Go untuk membuild aplikasi
    - name: Pull repository
      uses: actions/checkout@v2

    # Step 3: Instal dependensi dan build aplikasi Go
    - name: Build the Go app
      run: |
        go mod tidy
        go build -o my-go-app

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t my-go-app .

