name: Auto Pull Changes

on:
  schedule:
    # This schedules the action to run every day at 00:00 UTC.
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allows the workflow to be triggered manually in the GitHub UI.
  
jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull latest changes
      run: |
        git pull origin master

